#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml

registration_success:
    path: '/users'
    controller: App\Controller\UserController



# routes.yaml

update_user:
    path: '/user/{id}/update'
    controller: App\Controller\UserController::update
    methods: ['GET', 'POST']



# routes.yaml

delete_user:
    path: '/user/{id}/delete'
    controller: App\Controller\UserController::delete
    methods: ['GET', 'POST']


reactivate_user:
    path: /user/{id}/reactivate
    controller: 'App\Controller\UserController::reactivateUser'
    methods: ['POST']

adminDashboard:
    path: /admin/adminDashboard
    controller: 'App\Controller\HomeController::index'
   
userDashboard:
    path: /user/UserDashboard
    controller: 'App\Controller\HomeController::UserDash'
   

updateUser:
    path: /user/{id}/updateUser
    controller: 'App\Controller\UserController::updateUser'
   
login:
    path: /LoginRedirect
    controller: 'App\Controller\LoginController::loredirect'
   


user_list_pdf_download:
    path: '/download-user-list-pdf'
    controller: App\Controller\PdfController::downloadUserListPdf





museum_index:
    path: /
    controller: App\Controller\MuseumController::index

app_museum_search:
    path: /search
    controller: App\Controller\MuseumController::search
    methods: [GET]

recherche:
    path: /recherche
    controller: App\Controller\RechercheController::index
a_propos:
    path: /a-propos
    controller: App\Controller\AProposController::index

liste_musees:
    path: /musees
    controller: App\Controller\ClientMuseumController::listeMusees

accueil:
    path: /
    controller: App\Controller\AccueilController::index
    
details_musee:
    path: /musee/{id}
    controller: App\Controller\MuseumController::show

admin_dashboard:
    path: '/admin/adminDashboard'
    controller: 'App\Controller\HomeBackController::index'

admin_recherche:
    path: '/admin/museum/'
    controller: 'App\Controller\HomeBackController::RechercheByName'
    methods: ['POST']

pdf_generate:
    path: '/pdf'
    controller: 'App\Controller\PdfController::generatePdf'

app_pdf:
    path: /pdf
    controller: App\Controller\PdfController::generatePdf
    methods: [GET]

app_pdf1:
    path: /pdf1.2
    controller: App\Controller\PdfController::generatePdf1
    methods: [GET] 

app_pdf1.3:
    path: /pdf1.3
    controller: App\Controller\PdfController::generatePdf2
    methods: [GET] 

app_pdf2.1:
    path: /pdf2.1
    controller: App\Controller\PdfController::generatePdf3
    methods: [GET]

app_pdf2.2:
    path: /pdf2.2
    controller: App\Controller\PdfController::generatePdf4
    methods: [GET]

app_pdf2.3:
    path: /pdf2.3
    controller: App\Controller\PdfController::generatePdf5
    methods: [GET]

app_pdf3.1:
    path: /pdf3.1
    controller: App\Controller\PdfController::generatePdf6
    methods: [GET]

app_pdf3.2:
    path: /pdf3.2
    controller: App\Controller\PdfController::generatePdf7
    methods: [GET]
app_pdf3.3:
    path: /pdf3.3
    controller: App\Controller\PdfController::generatePdf8
    methods: [GET] 

app_pd4.1:
    path: /pdf4.1
    controller: App\Controller\PdfController::generatePdf9
    methods: [GET]    
app_pdf4.2:
    path: /pdf4.2
    controller: App\Controller\PdfController::generatePdf10
    methods: [GET]    
app_pdf4.3:
    path: /pdf4.3
    controller: App\Controller\PdfController::generatePdf11
    methods: [GET]    


app_pdf5.1:
    path: /pdf5.1
    controller: App\Controller\PdfController::generatePdf12
    methods: [GET]    
app_pdf5.2:
    path: /pdf5.2
    controller: App\Controller\PdfController::generatePdf13
    methods: [GET]    
app_pdf5.3:
    path: /pdf5.3
    controller: App\Controller\PdfController::generatePdf14
    methods: [GET]   