#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml

registration_success:
    path: '/users'
    controller: App\Controller\UserController



# routes.yaml

update_user:
    path: '/user/{id}/update'
    controller: App\Controller\UserController::update
    methods: ['GET', 'POST']



# routes.yaml

delete_user:
    path: '/user/{id}/delete'
    controller: App\Controller\UserController::delete
    methods: ['GET', 'POST']
